mpc_controller:
  # Simulation Mode
  sim: True

  # MPC Parameters
  horizon: 5
  dt: 0.05
  
  # Cost Function Weights
  weights:
    position: 8.0
    orientation: 4.0
    control: 0.02
    damping: 0.5
  
  # Active Motion Weights
  active_weights:
    linear: 15.0
    angular: 8.0
  
  # Robot Configuration
  arm_base_offset:
    x: 0.06
    y: -0.1
    z: 0.09
    yaw: 3.14159  # pi radians

  # Velocity scaling
  velocity:
    max_scale: 0.9
    min_scale: 0.4