mpc_controller:
  # Simulation Mode
  sim: False

  # MPC Parameters
  horizon: 1
  dt: 0.1
  
  # Cost Function Weights
  weights:
    position: 5.0
    orientation: 3.0
    control: 0.03
    smooth: 0.08
  
  # Active Motion Weights
  active_weights:
    linear: 50.0
    angular: 50.0
  
  # Robot Configuration
  arm_base_offset:
    x: 0.0
    y: 0.1
    z: 0.5
    yaw: 0.0  # No rotation according to your TF data