mpc_controller:
  # Simulation Mode
  sim: True

  # MPC Parameters
  horizon: 1
  dt: 0.1
  
  # Cost Function Weights
  weights:
    position: 20.0
    orientation: 3.0
    control: 0.1
    smooth: 0.3
    damping: 2.0
  
  # Active Motion Weights
  active_weights:
    linear: 20.0
    angular: 30.0
  
  # Robot Configuration
  arm_base_offset:
    x: 0.0
    y: 0.1
    z: 0.5
    yaw: 0.0