mpc_controller:
  # Simulation Mode
  sim: False

  # MPC Parameters
  horizon: 3
  dt: 0.05
  
  # Cost Function Weights
  weights:
    position: 3.0
    orientation: 2.0
    control: 0.005
    smooth: 0.02
  
  # Active Motion Weights
  active_weights:
    linear: 50.0
    angular: 5.0
  
  # Robot Configuration
  arm_base_offset:
    x: 0.06
    y: -0.1
    z: 0.09
    yaw: 3.14159  # pi radians

  # Velocity scaling
  velocity:
    max_scale: 0.9
    min_scale: 0.4